### ISSUE TITLE
More robust checks for ArcGIS services

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#190]
The logic that iterates over services seems to rely on ==2 or ==3 and that is not very robust.

**Comment by JorgeMartinezG** [comment]
This issue is related with #189. I replicated the issue and sent a PR. However, it is important to check how strict registry will be harvesting the services, using the endpoints given.
Arcgis endpoints usually come with services and/or folders with services. So, depending on the endpoint given, registry should be smart enough to detect whether the service comes from the root or the folder of services. 

Checking with some endpoints, I have found a pattern:

*Root service:* http://<endpoint_url>/rest/services/<service>/<server_type/>
*Folder service:* http://<endpoint_url>/rest/services/<folder>/<service>/<server_type/>

I found one way to discriminate the above pattern tokenizing with '/' and checking the length in order to harvest a single service. Any recommendation is appreciated.

**Comment by ingenieroariel** [comment]
Fixed.
