### ISSUE TITLE
ImageServer MapProxy verification

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#206]
With latest MapProxy, there is better support for ImageServers:

https://github.com/mapproxy/mapproxy/issues/235#issuecomment-245851000

@JorgeMartinezG can you compile a list of ImageServers from hh.worldmap.harvard.edu and try them against the latest MapProxy?

**Comment by JorgeMartinezG** [comment]
https://github.com/cga-harvard/HHypermap/commit/d96033c617493d223d71593c6dec89a2f127c3e3

In this commit I've enabled the service processing for ImageServer endpoints. Requirements.txt file was modified in order to use latest MapProxy.

Test was performed using these urls:
http://www.carsonproperty.info/ArcGIS/rest/services/2014_Aerials/ImageServer/?f=json
http://services.kgs.ku.edu/arcgis/rest/services/IMAGERY_LOCAL/Kingman_County_2005/ImageServer/?f=json
https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_global_mosaic/ImageServer/?f=json
http://www3.multco.us/ArcGIS/rest/services/Imagery/Urban_2015/ImageServer/?f=json
http://encdirect.noaa.gov/arcgis/rest/services/RNC/NOAA_RNC/ImageServer/?f=json

Visualization in maploom
![image](https://cloud.githubusercontent.com/assets/3285923/18597353/3c869184-7c13-11e6-92db-556ccd40ff93.png)

**Comment by ingenieroariel** [comment]
Thanks!
